"""Check that the documents quoting this analysis still agree with it.

    python tools/check_docs_drift.py

The notebook ends with a claim: "outputs/facts.json holds the computed values that
the accompanying project report quotes, so the two documents cannot drift apart."
That was true of how the report is *built* and enforced by nothing. Three ways it
could stop being true, none of which anything noticed:

  1. The README quotes about a hundred computed numbers and is written by hand.
     Re-run the notebook with one cleaning rule changed and every one of them can
     go stale while the file still reads as authoritative. It is the front door of
     the repository; it is the one document here nobody regenerates.

  2. tools/build_report.py reads 186 facts by name. Rename one in the notebook and
     the report build dies -- but only when someone runs it, and running it needs
     the 112 MB source workbook and a full notebook execution. So the breakage
     waits until the next person who wants a report, rather than the next push.

  3. The notebook itself is generated by tools/build_notebook.py, whose docstring
     says "Regenerating discards any edit made directly to the .ipynb". Nothing
     stopped an edit being made directly to the .ipynb, so the next regeneration
     silently reverted it.

All three are checked here, and all three are checked without the source data --
which is the point. The dataset is 112 MB and not committed, so any check that
needed it would not run in CI, and a check that does not run is a comment.

What this does NOT check: that facts.json is correct. It cannot -- that needs the
data and a notebook run. It checks that the documents say what facts.json says.
Wrong-but-consistent is still possible; wrong-and-inconsistent is not.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FACTS_PATH = ROOT / "outputs" / "facts.json"
README = ROOT / "README.md"
REPORT_BUILDER = ROOT / "tools" / "build_report.py"
NOTEBOOK_BUILDER = ROOT / "tools" / "build_notebook.py"

failures = 0


def fail(msg, detail=""):
    global failures
    failures += 1
    print(f"  FAIL  {msg}")
    for line in str(detail).splitlines():
        if line:
            print(f"        {line}")


def ok(msg):
    print(f"  ok    {msg}")


# --------------------------------------------------------------------------- #
# 1. the README quotes facts.json
# --------------------------------------------------------------------------- #
# key -> the format the README renders that fact in. The expected text is derived
# from facts.json at run time rather than written down here, so a re-run that
# changes a number leaves exactly one thing to edit: the README. A map holding
# the numbers themselves would be a third copy of them, which is the defect.
#
# The currency symbol is deliberately not part of any spec. The digits carry the
# check, and leaving it out keeps this file ASCII -- printing a pound sign to a
# cp1252 Windows console is a coin flip, and a checker that crashes on its own
# output is worse than no checker.
#
# Every entry below is a number distinctive enough that a coincidental match is
# implausible: four or more digits, or a percentage, or a decimal. Deliberately
# absent, because the README contains the bare digit too many times for a match
# to mean anything: k_chosen (4), silhouette_best_k (2), xmas_cohort_count (2),
# net_rank_movers (7), biggest_sale_cancel_gap_min (12). Those five are quoted in
# the README and are not covered. Said out loud because "30 of 35 checked" is a
# fact and "the README is checked" would be a claim.
README_FACTS = {
    # scale and cleaning
    "raw_rows": "{:,}",
    "rows_retained_pct": "{:.1f}%",
    "anonymous_rows_pct": "{:.1f}%",
    "anonymous_revenue_pct": "{:.1f}%",
    "id_coverage_pct": "{:.1f}%",
    # headline KPIs
    "total_revenue": "{:,.0f}",
    "orders": "{:,}",
    "customers": "{:,}",
    # concentration
    "top20pct_share": "{:.1f}%",
    "top20pct_customers": "{:,}",
    "top1pct_share": "{:.1f}%",
    "top1pct_customers": "{:,}",
    # segments
    "seg_champions_customers": "{:,}",
    "seg_champions_cust_pct": "{:.1f}%",
    "seg_champions_rev_pct": "{:.1f}%",
    "at_risk_customers": "{:,}",
    "at_risk_revenue": "{:,.0f}",
    # cohorts
    "preacquired_share_year2_pct": "{:.1f}%",
    "xmas_cohort_m3": "{:.1f}%",
    "nonxmas_cohort_m3": "{:.1f}%",
    "xmas_cohort_customers": "{:,}",
    # returns and the cancelled headline sale
    "return_value": "{:,.0f}",
    "return_rate_pct": "{:.2f}%",
    "worst_return_rate_pct": "{:.2f}%",
    "admin_reversal_value": "{:,.0f}",
    "credit_note_value": "{:,.0f}",
    "biggest_sale_value": "{:,.2f}",
    "biggest_sale_net": "{:,.2f}",
    # clustering
    "silhouette_best": "{}",
    "silhouette_at_k": "{}",
    "customer_concordance_pct": "{:.1f}%",
    # environment, which the README tabulates
    "env_python": "{}",
    "env_pandas": "{}",
    "env_numpy": "{}",
    "env_matplotlib": "{}",
    "env_sklearn": "{}",
    "env_openpyxl": "{}",
    "env_notebook": "{}",
}

#: Facts the README quotes as a magnitude, having already said which direction it
#: goes in prose ("that base *fell* GBP 1,248,022"). Checked against the absolute
#: value, because asserting the minus sign appears would assert a sentence rather
#: than a number.
ABS_FACTS = {"year2_change_in_existing_base": "{:,.0f}"}


def check_readme(facts):
    text = README.read_text(encoding="utf-8")
    missing = []
    for key, spec in {**README_FACTS, **ABS_FACTS}.items():
        if key not in facts:
            missing.append((key, "<not in facts.json>", None))
            continue
        value = facts[key]
        if key in ABS_FACTS and isinstance(value, (int, float)):
            value = abs(value)
        expected = spec.format(value)
        if expected not in text:
            missing.append((key, expected, facts[key]))
    if missing:
        fail(
            f"{len(missing)} fact(s) in outputs/facts.json are not what README.md says.",
            "\n".join(
                f"{key}: expected the README to contain {expected!r}"
                + (f" (fact value {raw!r})" if raw is not None else "")
                for key, expected, raw in missing
            )
            + "\n\nThe notebook has been re-run and the README has not been updated,\n"
            "or a fact was renamed. facts.json is the source of truth; edit the\n"
            "README to match it. Do not edit the map in this file to match the\n"
            "README -- the map holds formats, not numbers, precisely so that is\n"
            "not a way out.",
        )
    else:
        total = len(README_FACTS) + len(ABS_FACTS)
        ok(f"README.md agrees with facts.json on all {total} checked number(s)")

    # The README describes this check, and in doing so quotes two counts. Writing
    # them created two more numbers with nothing behind them, in the document this
    # file exists to stop that happening to. So they are checked. Cheap, and the
    # alternative was deleting two genuinely useful figures.
    claimed = re.search(r"(\d+) numbers in this README", text)
    if not claimed:
        fail("README.md no longer states how many of its numbers are checked.",
             "Either restore the figure or drop this assertion; do not leave a\n"
             "sentence that used to carry one.")
    elif int(claimed.group(1)) != len(README_FACTS) + len(ABS_FACTS):
        fail(
            f"README.md says {claimed.group(1)} of its numbers are checked; "
            f"this file checks {len(README_FACTS) + len(ABS_FACTS)}.",
            "Update the README.",
        )

    facts_claimed = re.search(r"all (\d+)\s*\n?\s*facts `build_report\.py` reads", text)
    if facts_claimed:
        real = len(set(re.findall(
            r"""\bF\[['"]([^'"]+)['"]\]""",
            REPORT_BUILDER.read_text(encoding="utf-8"))))
        if int(facts_claimed.group(1)) != real:
            fail(
                f"README.md says build_report.py reads {facts_claimed.group(1)} facts; "
                f"it reads {real}.",
                "Update the README.",
            )


# --------------------------------------------------------------------------- #
# 2. the report builder reads only facts that exist
# --------------------------------------------------------------------------- #

def check_report_builder(payload):
    src = REPORT_BUILDER.read_text(encoding="utf-8")

    # The static read below is only complete while every access is a literal. One
    # F[name] with a variable in it and this check starts quietly passing over
    # whatever that variable holds, so the assumption is asserted rather than
    # assumed.
    dynamic = re.findall(r"""\bF\[(?!['"])[^\]]{0,40}\]""", src)
    if dynamic:
        fail(
            "build_report.py now reads a fact through a variable: " + ", ".join(dynamic),
            "This check extracts literal keys only, so it can no longer claim to\n"
            "cover every fact the report reads. Either keep the accesses literal\n"
            "or teach this check to resolve them.",
        )

    keys = set(re.findall(r"""\bF\[['"]([^'"]+)['"]\]""", src))
    sections = set(re.findall(r"""\bpayload\[['"]([^'"]+)['"]\]""", src))

    absent = sorted(keys - set(payload["facts"]))
    if absent:
        fail(
            f"build_report.py reads {len(absent)} fact(s) that facts.json does not have: "
            + ", ".join(absent),
            "The report build dies on the first one. It needs the 112 MB workbook\n"
            "and a full notebook run to find that out, which is why this is here.",
        )
    absent_sections = sorted(sections - set(payload))
    if absent_sections:
        fail(
            "build_report.py reads missing top-level section(s): " + ", ".join(absent_sections)
        )
    if not absent and not absent_sections and not dynamic:
        ok(
            f"build_report.py's {len(keys)} fact(s) and {len(sections)} section(s) "
            f"all exist in facts.json"
        )


# --------------------------------------------------------------------------- #
# 3. the notebook has not been hand-edited
# --------------------------------------------------------------------------- #

def check_notebook_is_generated():
    proc = subprocess.run(
        [sys.executable, str(NOTEBOOK_BUILDER), "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    out = (proc.stdout + proc.stderr).strip()
    if proc.returncode == 0:
        ok(out.splitlines()[-1] if out else "notebook matches build_notebook.py")
    else:
        fail("the committed notebook does not match tools/build_notebook.py", out)


# --------------------------------------------------------------------------- #

def main():
    if not FACTS_PATH.exists():
        sys.exit(
            f"missing {FACTS_PATH.relative_to(ROOT)} -- it is committed, so this "
            "means an incomplete checkout rather than a missing notebook run."
        )
    payload = json.loads(FACTS_PATH.read_text(encoding="utf-8"))

    print("  -- README.md against outputs/facts.json --")
    check_readme(payload["facts"])
    print()
    print("  -- tools/build_report.py against outputs/facts.json --")
    check_report_builder(payload)
    print()
    print("  -- the notebook against tools/build_notebook.py --")
    check_notebook_is_generated()
    print()

    if failures:
        print(f"  {failures} failure(s). The documents and the analysis disagree.")
        return 1
    print("  the documents still say what the analysis computed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
